# -*- coding: utf-8 -*-
"""
High Schools Configuration for Teacher Verification
Contains K12 schools and high schools for random selection
FILTERED: Removed Elementary/Middle/Primary schools to avoid fraud detection
"""

import random

# High Schools for Teacher Verification (filtered - no elementary/middle schools)
HIGH_SCHOOLS = [
    {"id": 11455510, "idExtended": "11455510", "name": "Discovery Education", "city": "Springfield", "state": "VA", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4508226, "idExtended": "4508226", "name": "De La Salle High School", "city": "Concord", "state": "CA", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4669179, "idExtended": "4669179", "name": "De Paul Catholic High School", "city": "Wayne", "state": "NJ", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 225592, "idExtended": "225592", "name": "De Soto High School", "city": "De Soto", "state": "KS", "country": "US", "type": "K12"},
    {"id": 3997849, "idExtended": "3997849", "name": "De Pere High", "city": "De Pere", "state": "WI", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4008107, "idExtended": "4008107", "name": "De Soto High School", "city": "De Soto", "state": "KS", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 209550, "idExtended": "209550", "name": "De Forest Area High School", "city": "Deforest", "state": "WI", "country": "US", "type": "K12"},
    {"id": 3553937, "idExtended": "3553937", "name": "De Toledo High School", "city": "West Hills", "state": "CA", "country": "US", "type": "K12"},
    {"id": 262590, "idExtended": "262590", "name": "De La Salle High School", "city": "Concord", "state": "CA", "country": "US", "type": "K12"},
    {"id": 263592, "idExtended": "263592", "name": "De Anza Senior High School", "city": "El Sobrante", "state": "CA", "country": "US", "type": "K12"},
    {"id": 3515553, "idExtended": "3515553", "name": "De Soto Area School District", "city": "De Soto", "state": "WI", "country": "US", "type": "K12"},
    {"id": 3539990, "idExtended": "3539990", "name": "De Anza Magnet School", "city": "El Centro", "state": "CA", "country": "US", "type": "K12"},
    {"id": 3526341, "idExtended": "3526341", "name": "De Soto Unified School District 232", "city": "De Soto", "state": "KS", "country": "US", "type": "K12"},
    {"id": 4664982, "idExtended": "4664982", "name": "De La Salle High School", "city": "Minneapolis", "state": "MN", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4664983, "idExtended": "4664983", "name": "De Forest Area High School", "city": "Deforest", "state": "WI", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 210141, "idExtended": "210141", "name": "De Pere High School", "city": "De Pere", "state": "WI", "country": "US", "type": "K12"},
    {"id": 4000803, "idExtended": "4000803", "name": "De Anza High", "city": "Richmond", "state": "CA", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4508228, "idExtended": "4508228", "name": "De Smet Jesuit High School", "city": "St. Louis", "state": "MO", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4508225, "idExtended": "4508225", "name": "De La Salle Collegiate High School", "city": "Warren", "state": "MI", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3494681, "idExtended": "3494681", "name": "Mullica Township School District", "city": "Elwood", "state": "NJ", "country": "US", "type": "K12"},
    {"id": 222916, "idExtended": "222916", "name": "Mullanphy Botanical Gardens", "city": "Saint Louis", "state": "MO", "country": "US", "type": "K12"},
    {"id": 3532075, "idExtended": "3532075", "name": "Mullin Independent School District", "city": "Mullin", "state": "TX", "country": "US", "type": "K12"},
    {"id": 3994116, "idExtended": "3994116", "name": "Clearview Regional High School", "city": "Mullica Hill", "state": "NJ", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 177729, "idExtended": "177729", "name": "Mullins High School", "city": "Mullins", "state": "SC", "country": "US", "type": "K12"},
    {"id": 3527832, "idExtended": "3527832", "name": "Mullen Public Schools", "city": "Mullen", "state": "NE", "country": "US", "type": "K12"},
    {"id": 146528, "idExtended": "146528", "name": "Mullein Hill Christian Academy", "city": "Lakeville", "state": "MA", "country": "US", "type": "K12"},
    {"id": 177730, "idExtended": "177730", "name": "Mullins Marion Christian School", "city": "Mullins", "state": "SC", "country": "US", "type": "K12"},
    {"id": 228339, "idExtended": "228339", "name": "Mullen High School", "city": "Mullen", "state": "NE", "country": "US", "type": "K12"},
    {"id": 4012207, "idExtended": "4012207", "name": "Mullins High", "city": "Mullins", "state": "SC", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4005804, "idExtended": "4005804", "name": "Academy For Careers And Technology", "city": "Mullins", "state": "SC", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4665142, "idExtended": "4665142", "name": "Clearview Reg High School", "city": "Mullica Hill", "state": "NJ", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4671957, "idExtended": "4671957", "name": "Elementary School At Eustis", "city": "Eustis", "state": "NE", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 10043113, "idExtended": "10043113", "name": "LifeTech Academy", "city": "Lansing", "state": "MI", "country": "US", "type": "K12"},
    {"id": 4671956, "idExtended": "4671956", "name": "Elementary School At Sumner", "city": "Sumner", "state": "NE", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4008256, "idExtended": "4008256", "name": "Discipline Alternative Education Program", "city": "Houston", "state": "TX", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 272735, "idExtended": "272735", "name": "Dot Lake School", "city": "Dot Lake", "state": "AK", "country": "US", "type": "K12"},
    {"id": 3990211, "idExtended": "3990211", "name": "Dot Lake School", "city": "Dot Lake", "state": "AK", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3538825, "idExtended": "3538825", "name": "Green Dot Public Schools", "city": "Los Angeles", "state": "CA", "country": "US", "type": "K12"},
    {"id": 4582092, "idExtended": "4582092", "name": "Clear Dot Charter School", "city": "Columbia", "state": "SC", "country": "US", "type": "K12"},
    {"id": 167978, "idExtended": "167978", "name": "Faa Dot Child Development Center", "city": "Washington", "state": "DC", "country": "US", "type": "K12"},
    {"id": 3543617, "idExtended": "3543617", "name": "Green Dot Public Schools Rainier Valley", "city": "Seattle", "state": "WA", "country": "US", "type": "K12"},
    {"id": 3543835, "idExtended": "3543835", "name": "Green Dot Public Schools Charter", "city": "Tacoma", "state": "WA", "country": "US", "type": "K12"},
    {"id": 3506767, "idExtended": "3506767", "name": "Dothan City Schools", "city": "Dothan", "state": "AL", "country": "US", "type": "K12"},
    {"id": 188774, "idExtended": "188774", "name": "Northside Methodist Church And Academy", "city": "Dothan", "state": "AL", "country": "US", "type": "K12"},
    {"id": 188778, "idExtended": "188778", "name": "Providence Christian School", "city": "Dothan", "state": "AL", "country": "US", "type": "K12"},
    {"id": 188782, "idExtended": "188782", "name": "Highlands Elementary School", "city": "Dothan", "state": "AL", "country": "US", "type": "K12"},
    {"id": 10081897, "idExtended": "10081897", "name": "Dothan Preparatory Academy", "city": "Dothan", "state": "AL", "country": "US", "type": "K12"},
    {"id": 188768, "idExtended": "188768", "name": "Houston Academy", "city": "Dothan", "state": "AL", "country": "US", "type": "K12"},
    {"id": 188757, "idExtended": "188757", "name": "Rehobeth High School", "city": "Dothan", "state": "AL", "country": "US", "type": "K12"},
    {"id": 3506765, "idExtended": "3506765", "name": "Houston County Schools", "city": "Dothan", "state": "AL", "country": "US", "type": "K12"},
    {"id": 188748, "idExtended": "188748", "name": "Dothan High School", "city": "Dothan", "state": "AL", "country": "US", "type": "K12"},
    {"id": 149082, "idExtended": "149082", "name": "Dothan Brook School", "city": "White River Junction", "state": "VT", "country": "US", "type": "K12"},
    {"id": 4720339, "idExtended": "4720339", "name": "Houston Academy", "city": "Dothan", "state": "AL", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3990038, "idExtended": "3990038", "name": "Dothan High School", "city": "Dothan", "state": "AL", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4002963, "idExtended": "4002963", "name": "Rehobeth High School", "city": "Dothan", "state": "AL", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 188779, "idExtended": "188779", "name": "Westgate Christian School", "city": "Dothan", "state": "AL", "country": "US", "type": "K12"},
    {"id": 10253618, "idExtended": "10253618", "name": "Harvest Christian School", "city": "Dothan", "state": "AL", "country": "US", "type": "K12"},
    {"id": 188746, "idExtended": "188746", "name": "Beverlye Magnet School", "city": "Dothan", "state": "AL", "country": "US", "type": "K12"},
    {"id": 188780, "idExtended": "188780", "name": "Emmanuel Christian School", "city": "Dothan", "state": "AL", "country": "US", "type": "K12"},
    {"id": 188752, "idExtended": "188752", "name": "Heard Magnet School", "city": "Dothan", "state": "AL", "country": "US", "type": "K12"},
    {"id": 188764, "idExtended": "188764", "name": "Carver Magnet School For Mathematics, Sc", "city": "Dothan", "state": "AL", "country": "US", "type": "K12"},
    {"id": 4012931, "idExtended": "4012931", "name": "Opportunity High School", "city": "City", "state": "NM", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4666461, "idExtended": "4666461", "name": "City Polytechnic High School Of Engineering, Architecture And Technology", "city": "Brooklyn", "state": "NY", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 191201, "idExtended": "191201", "name": "City University School Of Liberal Arts", "city": "Memphis", "state": "TN", "country": "US", "type": "K12"},
    {"id": 10006125, "idExtended": "10006125", "name": "City Colleges Of Chicago - Harry S Truman", "city": "Chicago", "state": "IL", "country": "US", "type": "K12"},
    {"id": 10068767, "idExtended": "10068767", "name": "City Colleges Of Chicago-Richard J Daley College", "city": "Chicago", "state": "IL", "country": "US", "type": "K12"},
    {"id": 253615, "idExtended": "253615", "name": "City Of Angels (Indep. Study)", "city": "Los Angeles", "state": "CA", "country": "US", "type": "K12"},
    {"id": 10157701, "idExtended": "10157701", "name": "City Polytechnic High School of Engineering, Architecture, and Technology", "city": "Brooklyn", "state": "NY", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3524139, "idExtended": "3524139", "name": "City Garden Montessori", "city": "Saint Louis", "state": "MO", "country": "US", "type": "K12"},
    {"id": 3528446, "idExtended": "3528446", "name": "City Of Monroe School Board", "city": "Monroe", "state": "LA", "country": "US", "type": "K12"},
    {"id": 257169, "idExtended": "257169", "name": "City Tree Christian", "city": "San Diego", "state": "CA", "country": "US", "type": "K12"},
    {"id": 3993498, "idExtended": "3993498", "name": "City Academy", "city": "Saint Paul", "state": "MN", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3528203, "idExtended": "3528203", "name": "City Of Bogalusa School Board", "city": "Bogalusa", "state": "LA", "country": "US", "type": "K12"},
    {"id": 3498338, "idExtended": "3498338", "name": "City Charter High School (District)", "city": "Pittsburgh", "state": "PA", "country": "US", "type": "K12"},
    {"id": 180406, "idExtended": "180406", "name": "City Park School", "city": "Dalton", "state": "GA", "country": "US", "type": "K12"},
    {"id": 3501607, "idExtended": "3501607", "name": "City Neighbors High School", "city": "Baltimore", "state": "MD", "country": "US", "type": "K12"},
    {"id": 10495499, "idExtended": "10495499", "name": "City Christian School", "city": "Ventura", "state": "CA", "country": "US", "type": "K12"},
    {"id": 4005722, "idExtended": "4005722", "name": "City College Academy Of The Arts", "city": "New York", "state": "NY", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 268164, "idExtended": "268164", "name": "City View Charter School", "city": "Hillsboro", "state": "OR", "country": "US", "type": "K12"},
    {"id": 3538850, "idExtended": "3538850", "name": "City Language Immersion Charter", "city": "Los Angeles", "state": "CA", "country": "US", "type": "K12"},
    {"id": 3518687, "idExtended": "3518687", "name": "Park", "city": "Livingston", "state": "MT", "country": "US", "type": "K12"},
    {"id": 3519746, "idExtended": "3519746", "name": "Park Ridge Community Consolidated School District 64", "city": "Park Ridge", "state": "IL", "country": "US", "type": "K12"},
    {"id": 10206573, "idExtended": "10206573", "name": "Park Maitland School", "city": "Winter Park", "state": "FL", "country": "US", "type": "K12"},
    {"id": 3997396, "idExtended": "3997396", "name": "Park City High", "city": "Park City", "state": "UT", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 247564, "idExtended": "247564", "name": "Park City High School", "city": "Park City", "state": "UT", "country": "US", "type": "K12"},
    {"id": 152572, "idExtended": "152572", "name": "Park Ridge High School", "city": "Park Ridge", "state": "NJ", "country": "US", "type": "K12"},
    {"id": 218714, "idExtended": "218714", "name": "Park Junior High School", "city": "La Grange Park", "state": "IL", "country": "US", "type": "K12"},
    {"id": 3993842, "idExtended": "3993842", "name": "Park Hill South High", "city": "Riverside", "state": "MO", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3993841, "idExtended": "3993841", "name": "Park Hill High", "city": "Kansas City", "state": "MO", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4013124, "idExtended": "4013124", "name": "Park Center Ib World School", "city": "Brooklyn Park", "state": "MN", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3998048, "idExtended": "3998048", "name": "Park High", "city": "Racine", "state": "WI", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3706022, "idExtended": "3706022", "name": "Park Forest School District 163", "city": "Park Forest", "state": "IL", "country": "US", "type": "K12"},
    {"id": 3997483, "idExtended": "3997483", "name": "Park View High", "city": "Sterling", "state": "VA", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4673588, "idExtended": "4673588", "name": "Park School of Baltimore", "city": "Pikesville", "state": "MD", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3518295, "idExtended": "3518295", "name": "Park River Area 8", "city": "Park River", "state": "ND", "country": "US", "type": "K12"},
    {"id": 4670464, "idExtended": "4670464", "name": "Park Tudor School", "city": "Indianapolis", "state": "IN", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 213902, "idExtended": "213902", "name": "Park Rapids Senior High School", "city": "Park Rapids", "state": "MN", "country": "US", "type": "K12"},
    {"id": 247780, "idExtended": "247780", "name": "Park City Day School", "city": "Park City", "state": "UT", "country": "US", "type": "K12"},
    {"id": 3494006, "idExtended": "3494006", "name": "Park Ridge School District", "city": "Park Ridge", "state": "NJ", "country": "US", "type": "K12"},
    {"id": 3517095, "idExtended": "3517095", "name": "Park Rapids Public School District", "city": "Park Rapids", "state": "MN", "country": "US", "type": "K12"},
    {"id": 3707773, "idExtended": "3707773", "name": "Private School Services", "city": "Seattle", "state": "WA", "country": "US", "type": "K12"},
    {"id": 10202100, "idExtended": "10202100", "name": "Fusion Academy Alpharetta", "city": "Alpharetta", "state": "GA", "country": "US", "type": "K12"},
    {"id": 3997692, "idExtended": "3997692", "name": "Private School Services", "city": "Seattle", "state": "WA", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 10202101, "idExtended": "10202101", "name": "Fusion Academy Alpharetta", "city": "Alpharetta", "state": "GA", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 11319133, "idExtended": "11319133", "name": "Colegio Privado - Nobis Pacem", "city": "San Antonio", "state": "TX", "country": "US", "type": "K12"},
    {"id": 11319134, "idExtended": "11319134", "name": "Colegio Privado - Nobis Pacem", "city": "San Antonio", "state": "TX", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 259469, "idExtended": "259469", "name": "Fairmont Private School", "city": "Anaheim", "state": "CA", "country": "US", "type": "K12"},
    {"id": 10248858, "idExtended": "10248858", "name": "K12 Private Academy", "city": "Reston", "state": "VA", "country": "US", "type": "K12"},
    {"id": 229479, "idExtended": "229479", "name": "Central Private School", "city": "Baker", "state": "LA", "country": "US", "type": "K12"},
    {"id": 187353, "idExtended": "187353", "name": "Olivet Private School Inc", "city": "Port Saint Lucie", "state": "FL", "country": "US", "type": "K12"},
    {"id": 259275, "idExtended": "259275", "name": "Fairmont Private Schools, Edgewood Campus", "city": "Santa Ana", "state": "CA", "country": "US", "type": "K12"},
    {"id": 261494, "idExtended": "261494", "name": "Fairmont Private School", "city": "Fresno", "state": "CA", "country": "US", "type": "K12"},
    {"id": 5925328, "idExtended": "5925328", "name": "Bayer Private School", "city": "Glendale", "state": "AZ", "country": "US", "type": "K12"},
    {"id": 3549130, "idExtended": "3549130", "name": "Edison Private School", "city": "Hialeah", "state": "FL", "country": "US", "type": "K12"},
    {"id": 261913, "idExtended": "261913", "name": "Pinewood Private Of Los Altos", "city": "Los Altos", "state": "CA", "country": "US", "type": "K12"},
    {"id": 6801904, "idExtended": "6801904", "name": "K12 Private Academy", "city": "Herndon", "state": "VA", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 259671, "idExtended": "259671", "name": "Oakridge Private", "city": "Orange", "state": "CA", "country": "US", "type": "K12"},
    {"id": 3549732, "idExtended": "3549732", "name": "Prince Private Academy", "city": "Tampa", "state": "FL", "country": "US", "type": "K12"},
    {"id": 220467, "idExtended": "220467", "name": "Montessori Private Academy Inc", "city": "Rockford", "state": "IL", "country": "US", "type": "K12"},
    {"id": 259483, "idExtended": "259483", "name": "Hillsborough Private School", "city": "Anaheim", "state": "CA", "country": "US", "type": "K12"},
    {"id": 261900, "idExtended": "261900", "name": "Pinewood Private Upper Campus", "city": "Los Altos", "state": "CA", "country": "US", "type": "K12"},
    {"id": 10537603, "idExtended": "10537603", "name": "Guamani Private School", "city": "Guayama", "state": "PR", "country": "US", "type": "K12"},
    {"id": 10234078, "idExtended": "10234078", "name": "Pearblossom Private School K-8", "city": "Bogue Chitto", "state": "MS", "country": "US", "type": "K12"},
    {"id": 182501, "idExtended": "182501", "name": "Pensacola Private School Of Liberal Arts", "city": "Pensacola", "state": "FL", "country": "US", "type": "K12"},
    {"id": 4008034, "idExtended": "4008034", "name": "D. W. Daniel High", "city": "Central", "state": "SC", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 153239, "idExtended": "153239", "name": "Central", "city": "East Hanover", "state": "NJ", "country": "US", "type": "K12"},
    {"id": 177920, "idExtended": "177920", "name": "D W Daniel High School", "city": "Central", "state": "SC", "country": "US", "type": "K12"},
    {"id": 146492, "idExtended": "146492", "name": "Central", "city": "East Bridgewater", "state": "MA", "country": "US", "type": "K12"},
    {"id": 10513971, "idExtended": "10513971", "name": "Central Intermediate School", "city": "Central", "state": "LA", "country": "US", "type": "K12"},
    {"id": 152223, "idExtended": "152223", "name": "Central", "city": "Glen Rock", "state": "NJ", "country": "US", "type": "K12"},
    {"id": 10524306, "idExtended": "10524306", "name": "Central", "city": "Central", "state": "TN", "country": "US", "type": "K12"},
    {"id": 151463, "idExtended": "151463", "name": "Central", "city": "Warren", "state": "NJ", "country": "US", "type": "K12"},
    {"id": 3703997, "idExtended": "3703997", "name": "Central Islip Union Free School District", "city": "Central Islip", "state": "NY", "country": "US", "type": "K12"},
    {"id": 3997592, "idExtended": "3997592", "name": "Central Kitsap High School", "city": "Silverdale", "state": "WA", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4000473, "idExtended": "4000473", "name": "Central Union High", "city": "El Centro", "state": "CA", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4007284, "idExtended": "4007284", "name": "Central Davidson High", "city": "Lexington", "state": "NC", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3995973, "idExtended": "3995973", "name": "Central Bucks High School-East", "city": "Doylestown", "state": "PA", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3994949, "idExtended": "3994949", "name": "Central Academy Of Technology And Arts", "city": "Monroe", "state": "NC", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4007325, "idExtended": "4007325", "name": "Central High School - 41", "city": "Rapid City", "state": "SD", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3995972, "idExtended": "3995972", "name": "Central Bucks High School-West", "city": "Doylestown", "state": "PA", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4000462, "idExtended": "4000462", "name": "Central High East Campus", "city": "Fresno", "state": "CA", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4832896, "idExtended": "4832896", "name": "Central High (Omaha Ne)", "city": "Omaha", "state": "NE", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3491254, "idExtended": "3491254", "name": "Central Falls Public Schools", "city": "Central Falls", "state": "RI", "country": "US", "type": "K12"},
    {"id": 3993349, "idExtended": "3993349", "name": "Central High School", "city": "Traverse City", "state": "MI", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4666906, "idExtended": "4666906", "name": "Central Catholic High School -San Antonio", "city": "San Antonio", "state": "TX", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4000457, "idExtended": "4000457", "name": "Central Coast New Technical High", "city": "Nipomo", "state": "CA", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3996907, "idExtended": "3996907", "name": "N Garland High School", "city": "Garland", "state": "TX", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 186396, "idExtended": "186396", "name": "N Fort Myers Academy For The Arts", "city": "North Fort Myers", "state": "FL", "country": "US", "type": "K12"},
    {"id": 172027, "idExtended": "172027", "name": "N B Clements Junior High School", "city": "Prince George", "state": "VA", "country": "US", "type": "K12"},
    {"id": 4012611, "idExtended": "4012611", "name": "North Plainfield High School", "city": "N Plainfield", "state": "NJ", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 233840, "idExtended": "233840", "name": "N Garland High School", "city": "Garland", "state": "TX", "country": "US", "type": "K12"},
    {"id": 236573, "idExtended": "236573", "name": "N A Howry Intermediate", "city": "Fort Worth", "state": "TX", "country": "US", "type": "K12"},
    {"id": 3524093, "idExtended": "3524093", "name": "Nahed Chapman New American Academy", "city": "Saint Louis", "state": "MO", "country": "US", "type": "K12"},
    {"id": 152548, "idExtended": "152548", "name": "N A Bleshman Reg Day Para", "city": "Paramus", "state": "NJ", "country": "US", "type": "K12"},
    {"id": 3530786, "idExtended": "3530786", "name": "N W Harllee Early Childhood Center", "city": "Dallas", "state": "TX", "country": "US", "type": "K12"},
    {"id": 4009904, "idExtended": "4009904", "name": "High Technical High School", "city": "N Bergen", "state": "NJ", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4011450, "idExtended": "4011450", "name": "Manchester Junior-Sr High School", "city": "N Manchester", "state": "IN", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 6798702, "idExtended": "6798702", "name": "Patrick Henry Highschool", "city": "N Minneapolis", "state": "MN", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3522582, "idExtended": "3522582", "name": "N Pekin And Marquette Heights School District 102", "city": "Marquette Heights", "state": "IL", "country": "US", "type": "K12"},
    {"id": 4012519, "idExtended": "4012519", "name": "North Bergen High School", "city": "N Bergen", "state": "NJ", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 183945, "idExtended": "183945", "name": "N Dade Center For Modern Language", "city": "Opa Locka", "state": "FL", "country": "US", "type": "K12"},
    {"id": 3495080, "idExtended": "3495080", "name": "N J Reg Day-Piscataway School", "city": "Piscataway", "state": "NJ", "country": "US", "type": "K12"},
    {"id": 4012235, "idExtended": "4012235", "name": "N. A. Bleshman Regional Day School", "city": "Paramus", "state": "NJ", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 6797826, "idExtended": "6797826", "name": "Detroit Apple Association Supplementary Schools", "city": "New", "state": "MI", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3704681, "idExtended": "3704681", "name": "New Albany-Plain Local School District", "city": "New Albany", "state": "OH", "country": "US", "type": "K12"},
    {"id": 156742, "idExtended": "156742", "name": "New Rochelle High School", "city": "New Rochelle", "state": "NY", "country": "US", "type": "K12"},
    {"id": 3532452, "idExtended": "3532452", "name": "New Caney Independent School District", "city": "New Caney", "state": "TX", "country": "US", "type": "K12"},
    {"id": 3997490, "idExtended": "3997490", "name": "New Kent High", "city": "New Kent", "state": "VA", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3997099, "idExtended": "3997099", "name": "New Caney High School", "city": "New Caney", "state": "TX", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3495148, "idExtended": "3495148", "name": "New Brunswick School District", "city": "New Brunswick", "state": "NJ", "country": "US", "type": "K12"},
    {"id": 3497519, "idExtended": "3497519", "name": "New Hartford Central School District", "city": "New Hartford", "state": "NY", "country": "US", "type": "K12"},
    {"id": 3533138, "idExtended": "3533138", "name": "New Braunfels Independent School District", "city": "New Braunfels", "state": "TX", "country": "US", "type": "K12"},
    {"id": 157016, "idExtended": "157016", "name": "New Hyde Park Memorial Junior-Senior High School", "city": "New Hyde Park", "state": "NY", "country": "US", "type": "K12"},
    {"id": 3994656, "idExtended": "3994656", "name": "New Rochelle High School", "city": "New Rochelle", "state": "NY", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 146975, "idExtended": "146975", "name": "New Bedford High School", "city": "New Bedford", "state": "MA", "country": "US", "type": "K12"},
    {"id": 150887, "idExtended": "150887", "name": "New Canaan Country School", "city": "New Canaan", "state": "CT", "country": "US", "type": "K12"},
    {"id": 3492778, "idExtended": "3492778", "name": "New Britain School District", "city": "New Britain", "state": "CT", "country": "US", "type": "K12"},
    {"id": 3498796, "idExtended": "3498796", "name": "New Castle Area School District", "city": "New Castle", "state": "PA", "country": "US", "type": "K12"},
    {"id": 149647, "idExtended": "149647", "name": "New Britain High School", "city": "New Britain", "state": "CT", "country": "US", "type": "K12"},
    {"id": 3531086, "idExtended": "3531086", "name": "New Boston Independent School District", "city": "New Boston", "state": "TX", "country": "US", "type": "K12"},
    {"id": 150888, "idExtended": "150888", "name": "New Canaan High School", "city": "New Canaan", "state": "CT", "country": "US", "type": "K12"},
    {"id": 3491171, "idExtended": "3491171", "name": "New Bedford Public Schools", "city": "New Bedford", "state": "MA", "country": "US", "type": "K12"},
    {"id": 4002425, "idExtended": "4002425", "name": "New Milford High School", "city": "New Milford", "state": "CT", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 155042, "idExtended": "155042", "name": "New Brunswick High School", "city": "New Brunswick", "state": "NJ", "country": "US", "type": "K12"},
    {"id": 3705048, "idExtended": "3705048", "name": "New Albany-Floyd County Consolidated School", "city": "New Albany", "state": "IN", "country": "US", "type": "K12"},
    {"id": 3520574, "idExtended": "3520574", "name": "New Lenox School District 122", "city": "New Lenox", "state": "IL", "country": "US", "type": "K12"},
    {"id": 3705677, "idExtended": "3705677", "name": "New Prague Area Schools", "city": "New Prague", "state": "MN", "country": "US", "type": "K12"},
    {"id": 3515297, "idExtended": "3515297", "name": "New Richmond School District", "city": "New Richmond", "state": "WI", "country": "US", "type": "K12"},
    {"id": 226720, "idExtended": "226720", "name": "Caney Valley High School", "city": "Caney", "state": "KS", "country": "US", "type": "K12"},
    {"id": 3530205, "idExtended": "3530205", "name": "Caney Public Schools", "city": "Caney", "state": "OK", "country": "US", "type": "K12"},
    {"id": 3526752, "idExtended": "3526752", "name": "Caney Valley Unified School District 436", "city": "Caney", "state": "KS", "country": "US", "type": "K12"},
    {"id": 233130, "idExtended": "233130", "name": "Caney High School", "city": "Caney", "state": "OK", "country": "US", "type": "K12"},
    {"id": 4007082, "idExtended": "4007082", "name": "Caney Valley High", "city": "Caney", "state": "KS", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4007080, "idExtended": "4007080", "name": "Caney High School", "city": "Caney", "state": "OK", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 226719, "idExtended": "226719", "name": "Caney Valley Charter Academy", "city": "Caney", "state": "KS", "country": "US", "type": "K12"},
    {"id": 10523724, "idExtended": "10523724", "name": "CANEY ES", "city": "Caney", "state": "OK", "country": "US", "type": "K12"},
    {"id": 10314307, "idExtended": "10314307", "name": "Sacred Heart Catholic School", "city": "Caney", "state": "KS", "country": "US", "type": "K12"},
    {"id": 4007081, "idExtended": "4007081", "name": "Caney Valley Charter Academy", "city": "Caney", "state": "KS", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4672508, "idExtended": "4672508", "name": "Caney Elementary School", "city": "Caney", "state": "OK", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 238600, "idExtended": "238600", "name": "Caney Creek High School", "city": "Conroe", "state": "TX", "country": "US", "type": "K12"},
    {"id": 4007079, "idExtended": "4007079", "name": "Caney Creek High School", "city": "Conroe", "state": "TX", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 232688, "idExtended": "232688", "name": "Caney Valley High School", "city": "Ramona", "state": "OK", "country": "US", "type": "K12"},
    {"id": 4015880, "idExtended": "4015880", "name": "Valley School", "city": "Turkey", "state": "TX", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3529933, "idExtended": "3529933", "name": "Caney Valley Public Schools", "city": "Ramona", "state": "OK", "country": "US", "type": "K12"},
    {"id": 4015874, "idExtended": "4015874", "name": "Valley High School", "city": "Pine Grove", "state": "WV", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4004714, "idExtended": "4004714", "name": "Caney Valley High School", "city": "Ramona", "state": "OK", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4015873, "idExtended": "4015873", "name": "Valley High School", "city": "Smithers", "state": "WV", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3997387, "idExtended": "3997387", "name": "Valley High", "city": "Orderville", "state": "UT", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 231614, "idExtended": "231614", "name": "Corn Bible Academy", "city": "Corn", "state": "OK", "country": "US", "type": "K12"},
    {"id": 4668320, "idExtended": "4668320", "name": "Corn Bible Academy", "city": "Corn", "state": "OK", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3553227, "idExtended": "3553227", "name": "Cornerstone Christian Schools", "city": "San Antonio", "state": "TX", "country": "US", "type": "K12"},
    {"id": 4007864, "idExtended": "4007864", "name": "Corner Canyon High", "city": "Draper", "state": "UT", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 159848, "idExtended": "159848", "name": "Cornwall Central High School", "city": "New Windsor", "state": "NY", "country": "US", "type": "K12"},
    {"id": 3706702, "idExtended": "3706702", "name": "Corning School District", "city": "Corning", "state": "AR", "country": "US", "type": "K12"},
    {"id": 3994465, "idExtended": "3994465", "name": "Cornwall Central High School", "city": "New Windsor", "state": "NY", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3497290, "idExtended": "3497290", "name": "Cornwall Central School District", "city": "Cornwall On Hudson", "state": "NY", "country": "US", "type": "K12"},
    {"id": 3515603, "idExtended": "3515603", "name": "Cornell School District", "city": "Cornell", "state": "WI", "country": "US", "type": "K12"},
    {"id": 3542605, "idExtended": "3542605", "name": "Corning Union High School District", "city": "Corning", "state": "CA", "country": "US", "type": "K12"},
    {"id": 4674377, "idExtended": "4674377", "name": "Cornerstone Christian Schools", "city": "San Antonio", "state": "TX", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4675110, "idExtended": "4675110", "name": "Cornerstone Church Academy", "city": "Defuniak Springs", "state": "FL", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 161808, "idExtended": "161808", "name": "Corning Christian Academy", "city": "Corning", "state": "NY", "country": "US", "type": "K12"},
    {"id": 4007865, "idExtended": "4007865", "name": "Cornerstone Charter Academy High School", "city": "Belle Isle", "state": "FL", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3998793, "idExtended": "3998793", "name": "Cornell High", "city": "Cornell", "state": "WI", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4007863, "idExtended": "4007863", "name": "Cornell High School", "city": "Coraopolis", "state": "PA", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 267000, "idExtended": "267000", "name": "Corning High School", "city": "Corning", "state": "CA", "country": "US", "type": "K12"},
    {"id": 210398, "idExtended": "210398", "name": "Cormier School And Early Learning", "city": "Green Bay", "state": "WI", "country": "US", "type": "K12"},
    {"id": 191826, "idExtended": "191826", "name": "Lake Cormorant High School", "city": "Lake Cormorant", "state": "MS", "country": "US", "type": "K12"},
    {"id": 3504707, "idExtended": "3504707", "name": "Mccormick County School District", "city": "Mc Cormick", "state": "SC", "country": "US", "type": "K12"},
    {"id": 4010837, "idExtended": "4010837", "name": "Lake Cormorant High", "city": "Lake Cormorant", "state": "MS", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3504705, "idExtended": "3504705", "name": "Mccormick High School", "city": "Mc Cormick", "state": "SC", "country": "US", "type": "K12"},
    {"id": 178276, "idExtended": "178276", "name": "John De La Howe High School", "city": "Mc Cormick", "state": "SC", "country": "US", "type": "K12"},
    {"id": 178277, "idExtended": "178277", "name": "L S Brice School", "city": "Mc Cormick", "state": "SC", "country": "US", "type": "K12"},
    {"id": 178278, "idExtended": "178278", "name": "Long Cane Academy", "city": "Mc Cormick", "state": "SC", "country": "US", "type": "K12"},
    {"id": 3504704, "idExtended": "3504704", "name": "John De La Howe School (District)", "city": "Mc Cormick", "state": "SC", "country": "US", "type": "K12"},
    {"id": 4663916, "idExtended": "4663916", "name": "Mccormick High School", "city": "Mc Cormick", "state": "SC", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4668897, "idExtended": "4668897", "name": "John De La Howe High School", "city": "Mc Cormick", "state": "SC", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 4670985, "idExtended": "4670985", "name": "Long Cane Academy", "city": "Mc Cormick", "state": "SC", "country": "US", "type": "HIGH_SCHOOL"},
    {"id": 3552402, "idExtended": "3552402", "name": "Hope School - Cormorant", "city": "Springfield", "state": "IL", "country": "US", "type": "K12"}
]


# US Names for Teacher Verification
FIRST_NAMES = [
    # Female names
    "Emma", "Olivia", "Ava", "Isabella", "Sophia", "Mia", "Charlotte", "Amelia",
    "Harper", "Evelyn", "Abigail", "Emily", "Elizabeth", "Sofia", "Avery",
    "Ella", "Scarlett", "Grace", "Chloe", "Victoria", "Riley", "Aria", "Lily",
    "Aurora", "Zoey", "Nora", "Camila", "Hannah", "Lillian", "Addison",
    "Eleanor", "Natalie", "Luna", "Savannah", "Brooklyn", "Leah", "Zoe",
    "Stella", "Hazel", "Ellie", "Paisley", "Audrey", "Skylar", "Violet",
    "Claire", "Bella", "Lucy", "Anna", "Caroline", "Genesis", "Aaliyah",
    "Kennedy", "Kinsley", "Allison", "Maya", "Sarah", "Madelyn", "Adeline",
    "Alexa", "Ariana", "Elena", "Gabriella", "Naomi", "Alice", "Sadie",
    "Hailey", "Eva", "Emilia", "Autumn", "Quinn", "Nevaeh", "Piper",
    # Male names
    "Liam", "Noah", "Oliver", "Elijah", "James", "William", "Benjamin",
    "Lucas", "Henry", "Theodore", "Jack", "Levi", "Alexander", "Mason",
    "Ethan", "Jacob", "Michael", "Daniel", "Logan", "Jackson", "Sebastian",
    "Aiden", "Matthew", "Samuel", "David", "Joseph", "Carter", "Owen",
    "Wyatt", "John", "Luke", "Gabriel", "Anthony", "Isaac", "Dylan",
    "Leo", "Lincoln", "Jaxon", "Asher", "Christopher", "Josiah", "Andrew",
    "Thomas", "Joshua", "Ezra", "Hudson", "Charles", "Caleb", "Isaiah",
    "Ryan", "Nathan", "Adrian", "Christian", "Maverick", "Colton", "Elias",
    "Aaron", "Eli", "Landon", "Jonathan", "Nolan", "Hunter", "Cameron",
    "Connor", "Santiago", "Jordan", "Cooper", "Brayden", "Roman", "Evan"
]

LAST_NAMES = [
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller",
    "Davis", "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez",
    "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin",
    "Lee", "Perez", "Thompson", "White", "Harris", "Sanchez", "Clark",
    "Ramirez", "Lewis", "Robinson", "Walker", "Young", "Allen", "King",
    "Wright", "Scott", "Torres", "Nguyen", "Hill", "Flores", "Green",
    "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell", "Mitchell",
    "Carter", "Roberts", "Gomez", "Phillips", "Evans", "Turner", "Diaz",
    "Parker", "Cruz", "Edwards", "Collins", "Reyes", "Stewart", "Morris",
    "Morales", "Murphy", "Cook", "Rogers", "Gutierrez", "Ortiz", "Morgan",
    "Cooper", "Peterson", "Bailey", "Reed", "Kelly", "Howard", "Ramos",
    "Kim", "Cox", "Ward", "Richardson", "Watson", "Brooks", "Chavez",
    "Wood", "James", "Bennett", "Gray", "Mendoza", "Ruiz", "Hughes"
]


def get_random_high_school():
    """Get a random high school from the list"""
    return random.choice(HIGH_SCHOOLS)


def get_high_school_by_id(school_id):
    """Get a high school by ID"""
    for school in HIGH_SCHOOLS:
        if str(school.get('id')) == str(school_id) or school.get('idExtended') == str(school_id):
            return school
    return None


def get_random_teacher_name():
    """Get a random teacher name"""
    return random.choice(FIRST_NAMES), random.choice(LAST_NAMES)
